### ISSUE TITLE
Blueprint

### ISSUE THREAD

**Issue by kkytola** [alma-n/Polya-lean#3]
Let us add a blueprint soon!

For now I only added comments in the code, but that is no substitute for project management. [leanblueprint](https://github.com/PatrickMassot/leanblueprint) is the tool to organize formalization projects.

**Comment by xhalo32** [comment]
I'm working on it (or just got it working).

**Comment by xhalo32** [comment]
I have pushed a minimal working blueprint. There is also a `watch-blueprint` script (in [flake.nix](https://github.com/alma-n/Polya-lean/blob/1cd4ac10fe1450bee1c51bdfe5556ea03aa7051a/flake.nix#L105)) to watch and recompile changes to the blueprint.

Feel free to start working on the content of the blueprint :)
